---
name: "tagged-release"

on:
  push:
    tags:
      - "v*"

permissions:
    contents: write
    packages: write

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    env:
      VERSION: ${{  github.ref_name }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Running govulncheck
        uses: Templum/govulncheck-action@main
        with:
          vulncheck-version: latest
          package: ./...
          github-token: ${{ secrets.SECURITY_EVENTS }}
          go-version: 1.22.4
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: linux
          goarch: amd64